version: '2.0'
services:
  mark-web:
    image: cylab/mark-web:1.3.3
    environment:
      - MARK_HOST=mark_mark_1
      - MARK_PORT=8080
    ports:
      - "8000:80"
    volumes:
      - mark_data:/mark/data
    depends_on:
      - mark
  mark:
    build:
      context: .
      dockerfile: Dockerfile-example
    environment:
      - MARK_MONGO_HOST=mark_mongo_1
    volumes:
      - mark_data:/mark/data
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    volumes:
      - mark_mongodbdata:/data/db

volumes:
  mark_data:
  mark_mongodbdata:
