version: '2.0'
services:
  mark-web:
    image: cylab/mark-web:1.5.1
    environment:
      - MARK_HOST=mark_mark_1
      - MARK_PORT=8080
    ports:
      - "8000:80"
    volumes:
      - data:/var/www/html/storage/app/data
    depends_on:
      - mark
  mark:
    build:
      context: .
      dockerfile: Dockerfile-example
    environment:
      - MARK_MONGO_HOST=mark_mongo_1
    volumes:
      - data:/mark/data
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    volumes:
      - mongo:/data/db

volumes:
  data:
  mongo:
